[manager]
show_hidden = false
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

[preview]
tab_size = 2
max_width = 600
max_height = 900

[opener]
edit = [{ run = '$EDITOR "$@"', block = true }]
